# Generated by Django 5.0.2 on 2024-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('showTimes', models.JSONField(max_length=50)),
                ('dateofrelease', models.DateField()),
                ('image', models.URLField(help_text='Enter the URL Movie Poster')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
