# Generated by Django 5.0.2 on 2024-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieback', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(max_length=10),
        ),
    ]
